name: Amplify Backend Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: write

concurrency:
  group: amplify-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            .next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      
      - name: Install dependencies
        run: |
          # Use npm install instead of ci due to package-lock sync issues
          npm install --no-audit
      
      - name: Auto-Fix Linting Issues
        id: lint-fix
        run: |
          echo "🔧 Attempting to auto-fix lint issues..."
          npm run lint:fix || npx eslint . --fix --ext .js,.jsx,.ts,.tsx || true
          
          if git diff --quiet; then
            echo "✅ No lint issues found or fixed"
            echo "fixed=false" >> $GITHUB_OUTPUT
          else
            echo "🔧 Lint issues were auto-fixed"
            echo "fixed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Auto-Fix Prettier Formatting
        id: prettier-fix
        run: |
          echo "🎨 Attempting to auto-fix formatting..."
          npx prettier --write "**/*.js" "**/*.jsx" "**/*.ts" "**/*.tsx" "**/*.css" "**/*.md" "**/*.json" --ignore-path .gitignore || true
          
          if git diff --quiet; then
            echo "✅ No formatting issues"
            echo "fixed=false" >> $GITHUB_OUTPUT
          else
            echo "🎨 Formatting was auto-fixed"
            echo "fixed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit Auto-Fixes
        if: steps.lint-fix.outputs.fixed == 'true' || steps.prettier-fix.outputs.fixed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add -A
          git commit -m "🤖 Auto-fix: linting and formatting issues [skip ci]"
          git push origin "main"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Trigger Amplify Build
        run: |
          # Trigger a new build in AWS Amplify
          aws amplify start-job \
            --app-id d32q73w0m2w4bq \
            --branch-name main \
            --job-type RELEASE \
            --region eu-north-1
          
          echo "✅ Amplify build triggered!"
